# Generated by Django 5.1.15 on 2026-10-01 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_issuenumbering_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('checked_out', '借出中'), ('returned', '已归还'), ('lost', '遗失')], default='checked_out', max_length=12, verbose_name='单据状态')),
                ('borrower', models.CharField(blank=True, max_length=100, verbose_name='借阅人')),
                ('checkout_at', models.DateTimeField(blank=True, null=True, verbose_name='借出时刻')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时刻')),
                ('return_at', models.DateTimeField(blank=True, null=True, verbose_name='归还时刻')),
                ('lost_at', models.DateTimeField(blank=True, null=True, verbose_name='报失时刻')),
                ('shelf_location', models.CharField(blank=True, max_length=100, verbose_name='借出时架位')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='已应用事件版本')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='serials.item')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='LoanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.UUIDField(db_index=True, unique=True, verbose_name='幂等标识')),
                ('seq', models.PositiveIntegerField(verbose_name='单内顺序')),
                ('type', models.CharField(choices=[('checkout', '借出'), ('return', '归还'), ('lost', '遗失')], max_length=10, verbose_name='事件类型')),
                ('occurred_at', models.DateTimeField(verbose_name='业务发生时间')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='入库时间')),
                ('actor', models.CharField(blank=True, max_length=100, verbose_name='操作员')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('borrower', models.CharField(blank=True, max_length=100, verbose_name='借阅人快照')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='到期时刻快照')),
                ('shelf_location', models.CharField(blank=True, max_length=100, verbose_name='架位快照')),
                ('applied', models.BooleanField(default=True, verbose_name='是否已应用')),
                ('superseded', models.BooleanField(default=False, verbose_name='迟到被覆盖')),
                ('reject_reason', models.CharField(blank=True, max_length=255, verbose_name='未生效原因')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loan_events', to='serials.item')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='serials.loan')),
            ],
            options={
                'ordering': ['loan_id', 'seq'],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['item', 'status'], name='serials_loa_item_id_d967d7_idx'),
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['checked_out', 'lost'])), fields=('item',), name='uniq_active_loan_per_item'),
        ),
        migrations.AddConstraint(
            model_name='loanevent',
            constraint=models.UniqueConstraint(fields=('loan', 'seq'), name='uniq_event_seq_per_loan'),
        ),
    ]
