# Generated by Django 5.1.15 on 2026-10-02 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serials', '0002_alter_issuenumbering_issue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='幂等标识')),
                ('due_date', models.DateField(verbose_name='到期日')),
                ('custody_location', models.CharField(default='流通台', max_length=100, verbose_name='借出保管位置')),
                ('status', models.CharField(choices=[('open', '在借'), ('closed', '已关闭')], default='open', max_length=10, verbose_name='单据状态')),
                ('close_reason', models.CharField(blank=True, choices=[('returned', '已归还'), ('lost', '遗失')], max_length=10, null=True, verbose_name='关闭原因')),
                ('is_overdue', models.BooleanField(default=False, verbose_name='已标记逾期')),
                ('checked_out_at', models.DateTimeField(verbose_name='借出时间')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='关闭时间')),
                ('last_seq', models.PositiveIntegerField(default=0, verbose_name='事件序号游标')),
                ('last_applied_occurred_at', models.DateTimeField(verbose_name='最近应用事件时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='loans', to='serials.item')),
            ],
            options={
                'verbose_name': '流通单据',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CirculationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('checkout', '借出'), ('return', '归还'), ('overdue', '逾期'), ('lost', '遗失')], max_length=10, verbose_name='事件类型')),
                ('idempotency_key', models.CharField(max_length=64, unique=True, verbose_name='幂等标识')),
                ('occurred_at', models.DateTimeField(verbose_name='发生时间')),
                ('seq', models.PositiveIntegerField(verbose_name='单据内顺序')),
                ('applied', models.BooleanField(default=True, verbose_name='已应用')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='serials.loan')),
            ],
            options={
                'verbose_name': '流通事件',
                'ordering': ['seq', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='loan',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('item',), name='unique_open_loan_per_item'),
        ),
        migrations.AlterUniqueTogether(
            name='circulationevent',
            unique_together={('loan', 'seq')},
        ),
    ]
